# Generated by Django 4.1.5 on 2023-04-24 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                ("truckid", models.IntegerField(primary_key=True, serialize=False)),
                ("whid", models.IntegerField(blank=True, null=True)),
                ("loca_x", models.IntegerField()),
                ("loca_y", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("traveling", "traveling"),
                            ("arrivewarehouse", "arrivewarehouse"),
                            ("delivering", "delivering"),
                        ],
                        default="idle",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("packageid", models.IntegerField(primary_key=True, serialize=False)),
                ("packagename", models.CharField(max_length=100)),
                ("whid", models.IntegerField()),
                ("dest_x", models.IntegerField()),
                ("dest_y", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("picking", "picking"),
                            ("loading", "loading"),
                            ("delivering", "delivering"),
                            ("arrived", "arrived"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="upsapp.truck",
                    ),
                ),
                (
                    "upsaccount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
    ]
